# Generated by Django 4.1.2 on 2022-10-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("type", models.CharField(max_length=30)),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
            },
        ),
    ]
