# Generated by Django 4.1.2 on 2022-10-18 17:34

import aurore.apps.cms.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.blocks.field_block
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0077_alter_revision_user"),
        ("wagtailimages", "0024_index_image_file_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="Write the headline for your website", max_length=255
                    ),
                ),
                (
                    "sub_headline",
                    models.CharField(
                        help_text="Write the sub-headline for your website",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "brand_logos",
                                wagtail.blocks.ListBlock(
                                    aurore.apps.cms.blocks.APIImageChooserBlock,
                                    help_text="Add brand logos",
                                    required=False,
                                ),
                            ),
                            (
                                "about_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title_and_text",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "title",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Add your title",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.TextBlock(
                                                            help_text="Add subtitle or additional text",
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                help_text="Add the title and subtitle for this section",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                aurore.apps.cms.blocks.SimpleCardBlock,
                                                help_text="Add about cards",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    required=False,
                                ),
                            ),
                            (
                                "explore_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title_and_text",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "title",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Add your title",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.TextBlock(
                                                            help_text="Add subtitle or additional text",
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                help_text="Add your title and subtitle for the explore section",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                aurore.apps.cms.blocks.MediaBlock,
                                                help_text="Add medias for the explore section",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    required=False,
                                ),
                            ),
                            (
                                "how_it_works_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title_and_text",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "title",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Add your title",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.TextBlock(
                                                            help_text="Add subtitle or additional text",
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                help_text="Add title and subtitle for this section",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                aurore.apps.cms.blocks.SimpleCardBlock,
                                                help_text="Add cards",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    required=False,
                                ),
                            ),
                            (
                                "project_roadmap_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title_and_text",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "title",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Add your title",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.TextBlock(
                                                            help_text="Add subtitle or additional text",
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                help_text="Title and subtitle for project roadmap section",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "cards",
                                            wagtail.blocks.ListBlock(
                                                aurore.apps.cms.blocks.SimpleCardBlock,
                                                help_text="Add roadmap items",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    required=False,
                                ),
                            ),
                            (
                                "categories_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title_and_text",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "title",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="Add your title",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.TextBlock(
                                                            help_text="Add subtitle or additional text",
                                                            required=False,
                                                        ),
                                                    ),
                                                ],
                                                help_text="Add your title and text",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "categories",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.field_block.CharBlock,
                                                help_text="Add categories",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    required=False,
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="content block",
                    ),
                ),
            ],
            options={
                "verbose_name": "homepage",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePageCarouselImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "carousel_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_images",
                        to="cms.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
