# Generated by Django 4.1.2 on 2022-10-22 20:20

import aurore.apps.cms.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.blocks.field_block
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "media",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "image",
                                    aurore.apps.cms.blocks.APIImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document",
                                    aurore.apps.cms.blocks.APIDocumentChooserBlock(
                                        required=False
                                    ),
                                ),
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        default="Learn More",
                                        help_text="This is the text that appears on the link or button",
                                        max_length=40,
                                        required=True,
                                    ),
                                ),
                                (
                                    "link_url",
                                    wagtail.blocks.URLBlock(
                                        help_text="If the link page above is selected, that will be used first.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "open_in_new_tab",
                                    wagtail.blocks.BooleanBlock(
                                        default=False, required=False
                                    ),
                                ),
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "text_and_title",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add your title", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add subtitle or additional text",
                                        required=False,
                                    ),
                                ),
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "card",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title_and_text",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Add your title",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.TextBlock(
                                                    help_text="Add subtitle or additional text",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        help_text="Add your title and text for this card",
                                        required=True,
                                    ),
                                ),
                                (
                                    "media",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                aurore.apps.cms.blocks.APIImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "document",
                                                aurore.apps.cms.blocks.APIDocumentChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        help_text="Add an image or document",
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    default="Learn More",
                                                    help_text="This is the text that appears on the link or button",
                                                    max_length=40,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "link_url",
                                                wagtail.blocks.URLBlock(
                                                    help_text="If the link page above is selected, that will be used first.",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "open_in_new_tab",
                                                wagtail.blocks.BooleanBlock(
                                                    default=False, required=False
                                                ),
                                            ),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "logos",
                        wagtail.blocks.ListBlock(
                            aurore.apps.cms.blocks.APIImageChooserBlock,
                            help_text="Add brand logos",
                            required=False,
                        ),
                    ),
                    (
                        "explore_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title_and_text",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Add your title",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.TextBlock(
                                                    help_text="Add subtitle or additional text",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        help_text="Add your title and subtitle for the explore section",
                                        required=True,
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        aurore.apps.cms.blocks.SimpleCardBlock,
                                        help_text="Add about cards",
                                        required=False,
                                    ),
                                ),
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "categories_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title_and_text",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    help_text="Add your title",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.TextBlock(
                                                    help_text="Add subtitle or additional text",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        help_text="Add your title and text",
                                        required=True,
                                    ),
                                ),
                                (
                                    "categories",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.field_block.CharBlock,
                                        help_text="Add categories",
                                        required=False,
                                    ),
                                ),
                            ],
                            required=False,
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="content block",
            ),
        ),
    ]
